import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useCityContext } from '../context/CityContext';
import { ALL_SERVICE_CODES, SERVICE_CLASSES } from '../data/serviceClasses';
import { SUITABILITY_CRITERIA } from '../data/suitabilityData';
import { generateCitySubnetPrefix, compressIPv6 } from '../lib/ip/ipv6Math';
import { calculateIPv4Subnet } from '../lib/ip/ipv4Math';
import { formatBigNumber, formatNumber } from '../lib/utils';
import {
  FileText,
  Printer,
  Download,
  Copy,
  Check,
  Award,
  Activity,
  Layers,
  ShieldCheck,
  CheckCircle2,
  ArrowRight,
  Sparkles,
  Server,
  Zap,
  Globe
} from 'lucide-react';
import { WhatAmILookingAt } from '../components/WhatAmILookingAt';

export const ReportExport: React.FC = () => {
  const navigate = useNavigate();
  const {
    config,
    totalCurrentDevices,
    projectedGrowthDevices,
    devicesByClass,
    ipv4DeficitInfo,
    suitabilityScore,
    activeDistrict
  } = useCityContext();

  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  // Markdown Summary Generator
  const generateMarkdownSummary = () => {
    return `# CityNet Smart Municipal Network - Addressing & Architecture Plan
**Generated for:** CityNet Smart City Authority
**Planning Horizon:** ${config.planningHorizonYears} Years | **YoY Growth Rate:** ${config.growthRatePct}%
**Districts:** ${config.districts} | **Total Current Endpoints:** ${formatNumber(totalCurrentDevices)} | **Projected:** ${formatNumber(projectedGrowthDevices)}

---

## 1. Executive Summary & Protocol Verdict
- **Verdict:** Recommended: Pure IPv6-First Architecture with 4-Phase Dual-Stack Transition.
- **IPv6 Composite Score:** ${suitabilityScore.ipv6Total} / 10 (${suitabilityScore.ipv6WeightedPercent}% Fit)
- **IPv4 Composite Score:** ${suitabilityScore.ipv4Total} / 10 (${suitabilityScore.ipv4WeightedPercent}% Fit)
- **Primary Justification:** IPv6 eliminates Carrier-Grade NAT (CGNAT) table bottlenecks, provides 4.29 billion /64 subnets under \`2001:db8::/32\`, and supports native SLAAC autoconfiguration for 150k+ sensors per district.

---

## 2. Municipal Fleet Breakdown
- **Environmental Sensors (Service 0x1):** ${formatNumber(devicesByClass.sensors)} units (SLAAC, 6LoWPAN / LoRaWAN)
- **Traffic Signal Controllers (Service 0x2):** ${formatNumber(devicesByClass.traffic)} units (Deterministic Static, C-ITS, DSCP AF41)
- **Surveillance & Edge AI (Service 0x3):** ${formatNumber(devicesByClass.surveillance)} units (DHCPv6, Multicast ff0e::, 4K Video)
- **Emergency Services & PSAP (Service 0x4):** ${formatNumber(devicesByClass.emergency)} units (Anycast, DHCPv6-PD /60, DSCP EF Strict Priority)

---

## 3. Hierarchical Addressing Scheme (RFC 3849 Prefix: 2001:db8::/32)
- **City Block:** 2001:0db8::/32
- **District Block:** 2001:0db8:DD00::/40 (8 bits -> Up to 256 Districts)
- **Service Slice:** 2001:0db8:DDS0::/44 (4 bits -> 16 Service Classes)
- **Zone Sector:** 2001:0db8:DDSZ::/48 (4 bits -> 16 Zones)
- **Subnet ID:** 2001:0db8:DDSZ:SSSS::/64 (16 bits -> 65,536 Subnets per Zone)

---

## 4. IPv4 Private Space Deficit Assessment
- **Usable 10.0.0.0/8 Capacity:** ${formatNumber(ipv4DeficitInfo.class10CleanMax)} addresses across ${config.districts} districts.
- **Current Deficit:** ${ipv4DeficitInfo.class10Exhausted ? `-${formatNumber(ipv4DeficitInfo.deficitTotal)} addresses (Exhausted!)` : 'Within Limits'}
- **NAT Architecture Required:** ${ipv4DeficitInfo.natTier}

---
*Generated by CityNet Address Planner | Antigravity AI Network Architecture Suite*
`;
  };

  // Copy Markdown
  const handleCopySummary = () => {
    const md = generateMarkdownSummary();
    navigator.clipboard.writeText(md);
    setCopiedKey('summary');
    setTimeout(() => setCopiedKey(null), 2000);
  };

  // Export JSON Config
  const handleExportJSON = () => {
    const data = {
      generator: 'CityNet Address Planner',
      timestamp: new Date().toISOString(),
      config,
      totalCurrentDevices,
      projectedGrowthDevices,
      suitabilityScore,
      ipv4DeficitInfo
    };
    const jsonStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(data, null, 2));
    const link = document.createElement('a');
    link.setAttribute('href', jsonStr);
    link.setAttribute('download', `CityNet_Configuration_${new Date().toISOString().slice(0, 10)}.json`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Export CSV
  const handleExportCSV = () => {
    const rows = [
      ['District', 'Service Code', 'Service Name', 'Zone', 'IPv6 Subnet Prefix (/64)', 'Default Gateway Router IP', 'VLAN Tag', 'QoS Priority', 'IPv4 Equivalent Subnet', 'Host Capacity']
    ];

    for (let d = 1; d <= config.districts; d++) {
      ALL_SERVICE_CODES.forEach(svc => {
        for (let zn = 1; zn <= 2; zn++) {
          const prefix = generateCitySubnetPrefix(d, svc.code, zn, 1);
          const gw = compressIPv6(`2001:0db8:${d.toString(16).padStart(2, '0')}${svc.code}${zn.toString(16)}:0001:0000:0000:0000:0001`);
          const vlan = `VLAN ${parseInt(svc.code, 16) * 100 + zn * 10}`;
          const qos = SERVICE_CLASSES[svc.classKey]?.qosDscp || 'Best Effort';
          const v4 = `10.${d}.${parseInt(svc.code, 16) * 16 + zn}.0/24`;
          rows.push([
            `District ${d}`,
            `0x${svc.code}`,
            svc.name,
            `Zone ${zn}`,
            prefix,
            gw,
            vlan,
            `"${qos}"`,
            v4,
            '18.4 Quintillion (IPv6) / 254 (IPv4)'
          ]);
        }
      });
    }

    const csvContent = 'data:text/csv;charset=utf-8,' + rows.map(e => e.join(',')).join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `CityNet_Full_Addressing_Plan_${config.districts}Districts.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-300">
      <div className="no-print">
        <WhatAmILookingAt
          title="Executive Architecture Summary & Export Portal"
          summary="An auto-generated master report consolidating the smart city scale requirements, weighted scoring verdict, 128-bit prefix allocations, and migration roadmap. Includes print-ready styling for PDF generation and complete CSV data export."
          keyPoints={[
            'Download as PDF: Formats the entire executive report for PDF print with clean white-background contrast.',
            'Export Plan (.CSV): Generates a production-ready spreadsheet mapping every district, service, zone, VLAN, and default gateway.',
            'Export Config (.JSON): Saves all input parameters and custom criteria weights for team archiving or programmatic ingestion.'
          ]}
          architectTip="Click 'Download as PDF' to invoke your browser's print dialog, with all navigation elements automatically hidden for a pristine print layout."
        />
      </div>

      {/* Header & Export Action Buttons */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-800 no-print">
        <div>
          <div className="flex items-center gap-2">
            <span className="p-2 rounded-xl bg-cyan-500/10 text-cyan-400 border border-cyan-500/30">
              <FileText className="w-5 h-5" />
            </span>
            <div>
              <h1 className="text-xl sm:text-2xl font-extrabold text-slate-100">
                Step 8: Executive Report & Export Center
              </h1>
              <p className="text-xs text-slate-400">
                Generate production deliverables, printable executive briefs, and structured CSV addressing maps
              </p>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap items-center gap-2.5">
          <button
            onClick={() => window.print()}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-slate-950 font-bold text-xs shadow-lg shadow-cyan-500/20 transition-all cursor-pointer"
          >
            <Printer className="w-4 h-4" />
            <span>Download as PDF (Print)</span>
          </button>

          <button
            onClick={handleExportCSV}
            className="flex items-center gap-2 px-3.5 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-200 border border-slate-700 text-xs font-semibold transition-colors cursor-pointer"
          >
            <Download className="w-4 h-4 text-cyan-400" />
            <span>Export Plan (.CSV)</span>
          </button>

          <button
            onClick={handleCopySummary}
            className="flex items-center gap-2 px-3.5 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-200 border border-slate-700 text-xs font-semibold transition-colors cursor-pointer"
          >
            {copiedKey === 'summary' ? (
              <>
                <Check className="w-4 h-4 text-emerald-400" />
                <span className="text-emerald-400">Copied Markdown!</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 text-cyan-400" />
                <span>Copy Summary</span>
              </>
            )}
          </button>

          <button
            onClick={handleExportJSON}
            className="flex items-center gap-2 px-3.5 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-200 border border-slate-700 text-xs font-semibold transition-colors cursor-pointer"
          >
            <Zap className="w-4 h-4 text-purple-400" />
            <span>Export Config (.JSON)</span>
          </button>
        </div>
      </div>

      {/* Printable Master Report Document Card */}
      <div className="p-6 sm:p-10 rounded-3xl bg-slate-900/90 border border-slate-800 shadow-2xl backdrop-blur-md space-y-8 card-print">
        {/* Document Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-slate-800">
          <div>
            <div className="flex items-center gap-2 text-cyan-400 font-mono font-bold text-xs uppercase tracking-widest">
              <Sparkles className="w-4 h-4" />
              CityNet Smart Municipal Network Architecture
            </div>
            <h2 className="text-2xl sm:text-3xl font-black text-white mt-1">
              IoT Addressing Plan & Protocol Assessment Report
            </h2>
            <p className="text-xs text-slate-400 mt-1">
              Assessment of IPv4 vs IPv6 suitability for high-density municipal IoT infrastructure
            </p>
          </div>

          <div className="text-left sm:text-right space-y-1 font-mono text-xs text-slate-400">
            <div>Doc ID: <strong className="text-slate-200">CN-ARCH-2026-v1.0</strong></div>
            <div>Generated: <span className="text-cyan-400">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span></div>
            <div>Scope: <span className="text-emerald-400">{config.districts} Municipal Districts</span></div>
          </div>
        </div>

        {/* Executive Verdict Banner */}
        <div className="p-6 rounded-2xl bg-gradient-to-r from-cyan-950/40 via-slate-950 to-blue-950/40 border border-cyan-500/40 space-y-3">
          <div className="flex items-center gap-2 text-emerald-400 font-mono font-bold text-xs">
            <CheckCircle2 className="w-4 h-4" />
            STRATEGIC ARCHITECTURAL RECOMMENDATION
          </div>
          <h3 className="text-xl font-bold text-white">
            Recommended: Pure IPv6-First Architecture with Phased Dual-Stack Transition
          </h3>
          <p className="text-xs text-slate-300 leading-relaxed">
            The mathematical and operational analysis conclusively demonstrates that IPv4 cannot sustain the smart city scale requirements ({formatNumber(totalCurrentDevices)} endpoints scaling to {formatNumber(projectedGrowthDevices)} over {config.planningHorizonYears} years). IPv6 provides virtually unlimited address headroom, eliminates Carrier-Grade NAT (CGNAT) failure points, extends sensor battery life by eliminating keep-alive packets, and enables SLAAC zero-touch onboarding.
          </p>
        </div>

        {/* 4 Core Summary Metrics */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 space-y-1">
            <span className="text-[10px] uppercase font-bold text-slate-400">Total City Endpoints</span>
            <div className="font-mono text-xl font-extrabold text-cyan-400">{formatNumber(totalCurrentDevices)}</div>
            <div className="text-[10px] text-slate-400">Across {config.districts} Districts</div>
          </div>

          <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 space-y-1">
            <span className="text-[10px] uppercase font-bold text-slate-400">{config.planningHorizonYears}-Yr Growth Target</span>
            <div className="font-mono text-xl font-extrabold text-emerald-400">{formatNumber(projectedGrowthDevices)}</div>
            <div className="text-[10px] text-slate-400">+{config.growthRatePct}% YoY Compound</div>
          </div>

          <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 space-y-1">
            <span className="text-[10px] uppercase font-bold text-slate-400">IPv6 /64 Capacity</span>
            <div className="font-mono text-xl font-extrabold text-purple-400">4.29 Billion</div>
            <div className="text-[10px] text-slate-400">In 2001:db8::/32 block</div>
          </div>

          <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 space-y-1">
            <span className="text-[10px] uppercase font-bold text-slate-400">IPv4 Private Deficit</span>
            <div className="font-mono text-xl font-extrabold text-rose-400">
              {ipv4DeficitInfo.class10Exhausted ? `-${formatBigNumber(ipv4DeficitInfo.deficitTotal)}` : '0 (OK)'}
            </div>
            <div className="text-[10px] text-slate-400">Requires CGNAT if exhausted</div>
          </div>
        </div>

        {/* Device Class Breakdown Table */}
        <div className="space-y-3">
          <h4 className="font-bold text-sm text-slate-200">
            1. Municipal IoT Device Fleet & QoS Classification
          </h4>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-slate-800 bg-slate-950/70 text-slate-400 uppercase tracking-wider text-[11px]">
                  <th className="py-3 px-4">Service Category</th>
                  <th className="py-3 px-4">Service Code</th>
                  <th className="py-3 px-4">City Volume</th>
                  <th className="py-3 px-4">VLAN Scope</th>
                  <th className="py-3 px-4">QoS / DSCP Priority</th>
                  <th className="py-3 px-4">Autoconfiguration Mechanism</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/70">
                {Object.values(SERVICE_CLASSES).map(sc => (
                  <tr key={sc.id} className="hover:bg-slate-850/50">
                    <td className="py-3 px-4 font-semibold text-slate-200">{sc.name}</td>
                    <td className="py-3 px-4 font-mono text-cyan-300">0x{sc.serviceCode}</td>
                    <td className="py-3 px-4 font-mono font-bold text-slate-100">
                      {formatNumber(devicesByClass[sc.id])}
                    </td>
                    <td className="py-3 px-4 font-mono text-slate-300">{sc.vlanRange}</td>
                    <td className="py-3 px-4 text-purple-300">{sc.qosDscp}</td>
                    <td className="py-3 px-4 text-slate-300">{sc.addressingMode.split('(')[0]}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* 128-Bit Addressing Architecture Hierarchy */}
        <div className="space-y-3">
          <h4 className="font-bold text-sm text-slate-200">
            2. 128-Bit Hierarchical Addressing Architecture (2001:db8:DDSZ:SSSS::/64)
          </h4>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3">
            {[
              { tier: 'Tier 1: City Allocation', prefix: '2001:0db8::/32', desc: 'IANA RFC 3849 Municipal Root Block (32 bits)' },
              { tier: 'Tier 2: District Block', prefix: '2001:0db8:DD00::/40', desc: '8 bits -> Up to 256 Municipal Districts' },
              { tier: 'Tier 3: Service Class', prefix: '2001:0db8:DDS0::/44', desc: '4 bits -> 16 Service Traffic Classes' },
              { tier: 'Tier 4: Zone / Site', prefix: '2001:0db8:DDSZ::/48', desc: '4 bits -> 16 Geographic Sector Zones' },
              { tier: 'Tier 5: Subnet ID', prefix: '2001:0db8:DDSZ:SSSS::/64', desc: '16 bits -> 65,536 Subnets per Zone' }
            ].map((t, idx) => (
              <div key={idx} className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800 space-y-1">
                <div className="text-[10px] uppercase font-bold text-cyan-400">{t.tier}</div>
                <div className="font-mono text-xs font-bold text-emerald-400">{t.prefix}</div>
                <div className="text-[10px] text-slate-400">{t.desc}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Sample Addressing Plan Table */}
        <div className="space-y-3">
          <h4 className="font-bold text-sm text-slate-200">
            3. Sample District 01 Subnet Allocations & VLAN Mappings
          </h4>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-slate-800 bg-slate-950/70 text-slate-400 uppercase tracking-wider text-[11px]">
                  <th className="py-3 px-4">Service Class</th>
                  <th className="py-3 px-4">Zone</th>
                  <th className="py-3 px-4">IPv6 /64 Subnet Prefix</th>
                  <th className="py-3 px-4">Default Gateway (VIP)</th>
                  <th className="py-3 px-4">VLAN ID</th>
                  <th className="py-3 px-4">IPv4 Reference Block</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/70 font-mono text-[11px]">
                {ALL_SERVICE_CODES.slice(0, 4).map(svc => (
                  <tr key={svc.code} className="hover:bg-slate-850/50">
                    <td className="py-3 px-4 font-sans text-slate-200 font-semibold">{svc.name}</td>
                    <td className="py-3 px-4 text-slate-400">Zone 1</td>
                    <td className="py-3 px-4 text-cyan-300 font-bold">
                      {generateCitySubnetPrefix(1, svc.code, 1, 1)}
                    </td>
                    <td className="py-3 px-4 text-sky-400">
                      {compressIPv6(`2001:0db8:01${svc.code}1:0001:0000:0000:0000:0001`)}
                    </td>
                    <td className="py-3 px-4 text-purple-300">
                      VLAN {parseInt(svc.code, 16) * 100 + 10}
                    </td>
                    <td className="py-3 px-4 text-amber-300/80">
                      10.1.{parseInt(svc.code, 16) * 16 + 1}.0/24
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Sign-Off Footer */}
        <div className="pt-6 border-t border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-slate-400">
          <div>
            Prepared by <strong className="text-slate-200">CityNet Senior Network Architecture Team</strong>
          </div>
          <div className="font-mono text-[11px]">
            Antigravity Enterprise NOC Suite • RFC 3849 / RFC 4291 / RFC 8200 Compliant
          </div>
        </div>
      </div>

      {/* Navigation Footer */}
      <div className="pt-4 flex justify-between no-print">
        <button
          onClick={() => navigate('/migration')}
          className="px-5 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-300 border border-slate-800 text-xs font-medium transition-colors"
        >
          ← Back to Migration Roadmap
        </button>

        <button
          onClick={() => navigate('/')}
          className="flex items-center gap-2 px-6 py-3 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-slate-950 font-bold text-sm shadow-lg shadow-cyan-500/25 transition-all cursor-pointer"
        >
          <span>Return to Overview</span>
          <ArrowRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
};
